### Obvious Sort

In [9]:
l = [10, 12, 7, 10, 8, 42, 35, 18]
x = []

while len(l) > 0:
    min_val = l[0]  # Assume the first element is the minimum
    for i in range(1, len(l)):  # Start from the second element
        if l[i] < min_val:
            min_val = l[i]  # Update min_val if a smaller element is found
    x.append(min_val)  # Append the smallest element found to x
    l.remove(min_val)  # Remove the smallest element from l

print(x)


[7, 8, 10, 10, 12, 18, 35, 42]


### Dot Product

In [13]:
import random

x = [1,7,3,4]
y = [8,6,3,2]

sum = 0 

for i in range(len(x)):
    sum = sum+x[i]*y[i]

print(sum)

67


In [16]:
# Matrix addition by first principles

dim=3 

r1=[1,2,3]
r2=[4,5,6]
r3=[7,8,9]

s1=[1,2,1]
s2=[6,2,3]
s3=[4,2,1]

A=[]
A.append(r1)
A.append(r2)
A.append(r3)

B=[]
B.append(s1)
B.append(s2)
B.append(s3)

print(A)
print(B)

C=[[0,0,0],[0,0,0],[0,0,0]]

for i in range(dim):
    for j in range(dim):
        C[i][j]=A[i][j]+B[i][j]

print(C)



[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1, 2, 1], [6, 2, 3], [4, 2, 1]]
[[2, 4, 4], [10, 7, 9], [11, 10, 10]]


In [17]:
dim=3 

r1=[1,2,3]
r2=[4,5,6]
r3=[7,8,9]

s1=[1,2,1]
s2=[6,2,3]
s3=[4,2,1]

A=[]
A.append(r1)
A.append(r2)
A.append(r3)

B=[]
B.append(s1)
B.append(s2)
B.append(s3)

print(A)
print(B)

#C=[[0,0,0],[0,0,0],[0,0,0]]



for i in range(dim):
    for j in range(dim):
        C[i][j]=0

for i in range(dim):
    for j in range(dim):
        C[i][j]=A[i][j]+B[i][j]

print(C)


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1, 2, 1], [6, 2, 3], [4, 2, 1]]
[[2, 4, 4], [10, 7, 9], [11, 10, 10]]


In [20]:
### Matrix Multiplication

#C[i][j] is the dot product of the ith row of A and the jth column of B
D=[[0,0,0],[0,0,0],[0,0,0]]

for i in range(dim):
    for j in range(dim):
        for k in range(dim):
            D[i][j]+=A[i][k]*B[k][j]



print(D)


[[25, 12, 10], [58, 30, 25], [91, 48, 40]]


In [21]:
# Now the Big Gun - Numpy

import numpy as np

X = np.mat(A)
Y = np.mat(B)
print(X*Y)

[[25 12 10]
 [58 30 25]
 [91 48 40]]
